 class EvenOdd 
 { 
     
           public static void main(String arg[])
           { 
        
              
                      int no=25;
                      if (no%2==0)
                      {                                                                                                                                         

                                System.out.println("no is even");  
                   
 
                      }
                      else     
                      { 
                               System.out.println("no is odd");
 
                         
                      }       
                     
 
           
        } 
}
  
